### ISSUE TITLE
Max call stack size when finding pointed world on empty model

### ISSUE THREAD

**Issue by MikeVezina** [MikeVezina/epistemic-reasoner#1]
Call stack from Heroku is as follows (recursive call):

(node:30) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
2020-11-08T21:05:53.286741+00:00 app[web.1]:     at ExplicitEpistemicModel.Graph.getPointedNode (/app/src/app/modules/core/models/graph.ts:537:5)
2020-11-08T21:05:53.286742+00:00 app[web.1]:     at ExplicitEpistemicModel.getPointedWorldID (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:173:21)
2020-11-08T21:05:53.286742+00:00 app[web.1]:     at ExplicitEpistemicModel.findPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:152:18)
2020-11-08T21:05:53.286743+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:44)
2020-11-08T21:05:53.286743+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.286744+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.286744+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.286744+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.286744+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.286745+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.286945+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-11-08T21:05:53.287087+00:00 app[web.1]: (node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-11-08T21:05:53.833179+00:00 app[web.1]: Creating new model with 0 worlds
2020-11-08T21:05:53.941975+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
2020-11-08T21:05:53.941977+00:00 app[web.1]:     at Function.[Symbol.hasInstance] (<anonymous>)
2020-11-08T21:05:53.941978+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:133:14)
2020-11-08T21:05:53.941979+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.941979+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.941980+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.941983+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.941983+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.942005+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.942006+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.942006+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:05:53.942123+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2020-11-08T21:06:36.413256+00:00 app[web.1]: Creating new model with 0 worlds
2020-11-08T21:06:36.449363+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
2020-11-08T21:06:36.449365+00:00 app[web.1]:     at Function.[Symbol.hasInstance] (<anonymous>)
2020-11-08T21:06:36.449369+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:133:14)
2020-11-08T21:06:36.449370+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:06:36.449370+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:06:36.449371+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:06:36.449371+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:06:36.449371+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:06:36.449372+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:06:36.449372+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:06:36.449372+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:06:36.457443+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2020-11-08T21:08:16.169296+00:00 app[web.1]: Creating new model with 0 worlds
2020-11-08T21:08:16.176701+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
2020-11-08T21:08:16.176704+00:00 app[web.1]:     at Function.[Symbol.hasInstance] (<anonymous>)
2020-11-08T21:08:16.176706+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:133:14)
2020-11-08T21:08:16.176706+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:08:16.176707+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:08:16.176707+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:08:16.176708+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:08:16.176708+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:08:16.176708+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:08:16.176709+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:08:16.176709+00:00 app[web.1]:     at ExplicitEpistemicModel.setPointedWorld (/app/src/app/modules/core/models/epistemicmodel/explicit-epistemic-model.ts:144:14)
2020-11-08T21:08:16.176851+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by MikeVezina** [comment]
Fixed: (Undefined value caused recursive call)
